export const EMPTY_CELLS_AROUND_BOARD = 2;

export const INITIAL_LETTER_POOL =
  "JJKKQQXXZZBBBCCCFFFHHHMMMPPPVVVWWWYYYGGGGLLLLLDDDDDDSSSSSSUUUUUUNNNNNNNNTTTTTTTTTRRRRRRRRROOOOOOOOOOOIIIIIIIIIIIIAAAAAAAAAAAAAEEEEEEEEEEEEEEEEEE"
    .split("")
    .map((letter, idx) => ({ id: `${letter}-${idx}`, letter }));
